package ap.c04.p01.superclassSubclass.constructor;


public class TestConstructor {
	public static void main(String[] args) {
		Dog d=new Dog("jaja", 10);
	}

}

class Animal {
	public String name;

	public Animal(String name) {
		this.name = name;
	}

	public void jump() {
		System.out.println();
	}
}

// page 149 'rules for subclasses'
// subclass should define its own constructors (not clear)

// subclass always have its own constructors
// including the default one generated by compiler (right)

// Dog
class Dog extends Animal {
	private int age;

	public Dog(String name, int age) {
		super(name);
		this.age=age;
	}
}
